CREATE TABLE [dbo].[Patient]
(
  GID INT NOT NULL,
  PATID INT NOT NULL PRIMARY KEY,
  FirstName NVARCHAR(50) NOT NULL,
  LastName NVARCHAR(50) NOT NULL,
  DateOfBirth DATE NOT NULL,
  Gender NVARCHAR(10) NULL,
  PhoneNumber NVARCHAR(20) NULL,
  Email NVARCHAR(100) NULL,
  Address NVARCHAR(255) NULL,
  City NVARCHAR(50) NULL,
  State NVARCHAR(50) NULL,
  PostalCode NVARCHAR(20) NULL,
  Country NVARCHAR(50) NULL,
  BloodType NVARCHAR(3) NULL,
  Allergies NVARCHAR(255) NULL,
  MedicalHistory NVARCHAR(MAX) NULL,
  CreatedAt DATETIME DEFAULT GETDATE(),
  UpdatedAt DATETIME DEFAULT GETDATE(),
  CONSTRAINT PK_Patient PRIMARY KEY CLUSTERED (GID, PATID)
)
